import re
import logging
from typing import List, Set, Dict

from retrieval.models import Citation
from generation.models import GeneratedAnswer, GenerationCitation
from generation.constants import CITATION_REGEX_PATTERN

logger = logging.getLogger(__name__)


class CitationExtractor:
    """
    Deterministically maps LLM inline citation markers back to retrieved evidence.
    
    Responsibility:
    Parses raw text, extracts bracketed numbers, and looks them up against the 
    strict citation_map generated by the PromptBuilder.
    """

    def extract(
        self, 
        answer: GeneratedAnswer, 
        citation_map: Dict[int, Citation]
    ) -> List[GenerationCitation]:
        
        raw_text = answer.answer
        matches = re.findall(CITATION_REGEX_PATTERN, raw_text)
        
        cited_indices: Set[int] = set()
        invalid_indices: Set[int] = set()
        total_markers = len(matches)
        
        # 1. Parse individual indices (handles formats like [1, 2])
        for match in matches:
            parts = [p.strip() for p in match.split(",")]
            for part in parts:
                if part.isdigit():
                    idx = int(part)
                    if idx in citation_map:
                        cited_indices.add(idx)
                    else:
                        invalid_indices.add(idx)
                        
        # 2. Build deterministic GenerationCitations
        valid_citations: List[GenerationCitation] = []
        for idx in sorted(cited_indices):
            base_citation = citation_map[idx]
            
            gen_citation = GenerationCitation(
                chunk_id=base_citation.chunk_id,
                document_id=base_citation.document_id,
                title=base_citation.title,
                source=base_citation.source,
                page=base_citation.page,
                score=base_citation.score,
                inline_reference=f"[{idx}]"
            )
            valid_citations.append(gen_citation)
            
        # 3. Rich Observability Telemetry
        logger.info(
            f"Citation Extraction | Markers found: {total_markers} | "
            f"Valid resolved: {len(valid_citations)} | "
            f"Invalid/Hallucinated dropped: {len(invalid_indices)}"
        )
        
        return valid_citations