# memory/conversation/history.py

from typing import List, Set, Optional
from memory.models import ConversationHistory, ConversationMessage, MessageRole

class ConversationHistoryService:
    """
    Pure domain service for manipulating ConversationHistory objects.
    
    Architecture Note:
    - STATELESS & PURE: No databases, no external dependencies.
    - IMMUTABLE: Every public method returns a brand-new ConversationHistory object.
    - TOKEN-AWARE: Handles slicing by both message count AND token budget.
    """

    def recalculate_totals(self, history: ConversationHistory) -> ConversationHistory:
        """Ensures the total counts match the actual list footprint."""
        return self._build_immutable_history(history.messages)

    def build_pruning_plan(self, history: ConversationHistory, keep_recent_n: int) -> 'PruningPlan': # type: ignore
        """Calculates exactly which messages to drop and what the new history will look like."""
        messages_to_summarize = self.get_messages_to_summarize(history, keep_recent_n)
        ids_to_remove = {msg.message_id for msg in messages_to_summarize}
        
        remaining = self.prune_by_ids(history, ids_to_remove)
        
        # Lazy import to avoid circular dependency with memory.models
        from memory.models import PruningPlan 
        return PruningPlan(message_ids_to_remove=ids_to_remove, remaining_history=remaining)

    def get_recent_messages_by_count(
        self, 
        history: ConversationHistory, 
        limit: int
    ) -> ConversationHistory:
        """Extracts the most recent N messages."""
        if limit <= 0 or not history.messages:
            return self._build_immutable_history([])
            
        return self._build_immutable_history(history.messages[-limit:])

    def get_recent_messages_by_tokens(
        self, 
        history: ConversationHistory, 
        max_tokens: int
    ) -> ConversationHistory:
        """
        Extracts the most recent messages that fit entirely within a token budget.
        Crucial for preventing context window blowouts.
        """
        if max_tokens <= 0 or not history.messages:
            return self._build_immutable_history([])

        allowed_messages = []
        current_tokens = 0

        for msg in reversed(history.messages):
            if current_tokens + msg.tokens > max_tokens:
                break
            allowed_messages.insert(0, msg) 
            current_tokens += msg.tokens

        return self._build_immutable_history(allowed_messages)

    def get_messages_to_summarize(
        self, 
        history: ConversationHistory, 
        keep_recent_n: int
    ) -> List[ConversationMessage]:
        """
        Identifies the older messages that should be compressed into a summary,
        leaving exactly `keep_recent_n` untouched at the end of the array.
        """
        if len(history.messages) <= keep_recent_n:
            return []
        
        return history.messages[:-keep_recent_n]

    def prune_by_ids(
        self, 
        history: ConversationHistory, 
        ids_to_remove: Set[str]
    ) -> ConversationHistory:
        """
        Drops specific messages from the history (e.g., messages that were just summarized).
        ID-based pruning is safer than position-based pruning and respects pinned/system messages.
        """
        retained_messages = [
            msg for msg in history.messages 
            if msg.message_id not in ids_to_remove
        ]
        return self._build_immutable_history(retained_messages)

    def filter_by_role(
        self, 
        history: ConversationHistory, 
        role: MessageRole
    ) -> ConversationHistory:
        """Isolates messages generated by a specific actor."""
        filtered = [msg for msg in history.messages if msg.role == role]
        return self._build_immutable_history(filtered)

    def get_last_user_message(self, history: ConversationHistory) -> Optional[ConversationMessage]:
        """Fast lookup for Self-Healing or Feedback subsystems."""
        for msg in reversed(history.messages):
            if msg.role == MessageRole.USER:
                return msg
        return None

    def get_last_assistant_message(self, history: ConversationHistory) -> Optional[ConversationMessage]:
        """Fast lookup for Citation Builders or Self-Healing."""
        for msg in reversed(history.messages):
            if msg.role == MessageRole.ASSISTANT:
                return msg
        return None

    def find_message_by_id(self, history: ConversationHistory, message_id: str) -> Optional[ConversationMessage]:
        """Retrieves a specific message for feedback, editing, or citation resolution."""
        for msg in history.messages:
            if msg.message_id == message_id:
                return msg
        return None

    def is_empty(self, history: ConversationHistory) -> bool:
        """Lightweight validation check."""
        return len(history.messages) == 0

    def merge_history(self, base: ConversationHistory, incoming: ConversationHistory) -> ConversationHistory:
        """
        Safely appends new messages while ignoring duplicates.
        Useful for resolving state if multiple streams (e.g., DB and WebSocket) arrive async.
        """
        existing_ids = {msg.message_id for msg in base.messages}
        merged = list(base.messages)
        
        for new_msg in incoming.messages:
            if new_msg.message_id not in existing_ids:
                merged.append(new_msg)
                
        return self._build_immutable_history(merged)

    def _build_immutable_history(self, messages: List[ConversationMessage]) -> ConversationHistory:
        """
        Private factory. Ensures every operation returns a mathematically perfect,
        newly minted object rather than mutating state.
        """
        return ConversationHistory(
            messages=messages,
            total_messages=len(messages),
            total_tokens=sum(msg.tokens for msg in messages)
        )