"""create knowledge_gaps table

Revision ID: 51f278e7250c
Revises: 7651905d3dac
Create Date: 2026-07-08 11:36:14.541046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '51f278e7250c'
down_revision: Union[str, Sequence[str], None] = '7651905d3dac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_gaps',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Internal database identifier.'),
    sa.Column('missing_topic', sa.String(length=300), nullable=False, comment="The canonical subject missing from the database (e.g., 'GPT-6')."),
    sa.Column('failed_queries', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False, comment='List of specific user phrasings that hit this gap.'),
    sa.Column('frequency', sa.Integer(), server_default=sa.text("1"), nullable=False, comment='Number of times this gap has been detected across all users.'),
    sa.Column('resolved', sa.Boolean(), server_default=sa.text("false"), nullable=False, comment='True if the IngestionPipeline has successfully learned this topic.'),
    sa.Column('first_detected', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='When this topic was first discovered missing.'),
    sa.Column('last_detected', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Most recent occurrence. Automatically updates when touched.'),
    sa.Column('last_query_id', sa.String(length=100), nullable=True, comment='Foreign correlation ID bridging back to evaluation_runs and distributed traces.'),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the IngestionPipeline successfully resolved the gap.'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('missing_topic')
    )
    op.create_index('ix_knowledge_gaps_freq_desc', 'knowledge_gaps', ['frequency'], unique=False, postgresql_using='btree')
    op.create_index('ix_knowledge_gaps_last_detected', 'knowledge_gaps', ['last_detected'], unique=False)
    op.create_index('ix_knowledge_gaps_resolved', 'knowledge_gaps', ['resolved'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_knowledge_gaps_resolved', table_name='knowledge_gaps')
    op.drop_index('ix_knowledge_gaps_last_detected', table_name='knowledge_gaps')
    op.drop_index('ix_knowledge_gaps_freq_desc', table_name='knowledge_gaps', postgresql_using='btree')
    op.drop_table('knowledge_gaps')
    # ### end Alembic commands ###